### PR TITLE
Added Swift Package Manager Support

### PR DESCRIPTION
**Pull request by vknabel**
This Pull Request adds support for the Swift Package Manager and updates the README.md accordingly.

As a drawback, the source files needed to be moved.

The podspec has been fixed to reflect these changes (assuming the next version will be 1.1.0)

### CODE REVIEW

**Comment by vknabel** [comment]
@seanparsons Thanks for the fast merge! But I am sorry to say I forgot to mention that the SwiftPM requires a tag like `1.1.0` to be set.

**Comment by seanparsons** [comment]
@vknabel What do you mean?

**Comment by vknabel** [comment]
@seanparsons The SwiftPM clones the repo and looks for version tags (branches are not supported). The selected tags must contain the `Package.swift` file. Currently the only tag is 1.0.0, which does not contain this PR. Therefore there needs to be a new tag set.

In my fork (of your fork of his fork :) ) I already added that tag: https://github.com/vknabel/SwiftTryCatch/releases/tag/1.1.0

**Comment by seanparsons** [comment]
@vknabel Righto!

**Pull request merged**
